// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBid-oC95Ltbkz_wOu2V1JtxFyHqF6_Juo',
    appId: '1:674000765643:web:95ffd3e3504633daf8914e',
    messagingSenderId: '674000765643',
    projectId: 'lost-and-found24142',
    authDomain: 'lost-and-found24142.firebaseapp.com',
    storageBucket: 'lost-and-found24142.firebasestorage.app',
    measurementId: 'G-WLBV8QSYS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu5g5po1sko35wiDrSFatH_hYyI2KZeUk',
    appId: '1:674000765643:android:7915081dbd1699f3f8914e',
    messagingSenderId: '674000765643',
    projectId: 'lost-and-found24142',
    storageBucket: 'lost-and-found24142.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJySZ9E4Q1M7MYjMCXMbkQP3tN900QFzM',
    appId: '1:674000765643:ios:5ce0aeb4675d0ba3f8914e',
    messagingSenderId: '674000765643',
    projectId: 'lost-and-found24142',
    storageBucket: 'lost-and-found24142.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJySZ9E4Q1M7MYjMCXMbkQP3tN900QFzM',
    appId: '1:674000765643:ios:5ce0aeb4675d0ba3f8914e',
    messagingSenderId: '674000765643',
    projectId: 'lost-and-found24142',
    storageBucket: 'lost-and-found24142.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBid-oC95Ltbkz_wOu2V1JtxFyHqF6_Juo',
    appId: '1:674000765643:web:cc60f879b9c1a07ef8914e',
    messagingSenderId: '674000765643',
    projectId: 'lost-and-found24142',
    authDomain: 'lost-and-found24142.firebaseapp.com',
    storageBucket: 'lost-and-found24142.firebasestorage.app',
    measurementId: 'G-GYH1L1YNG9',
  );
}
